test:
  host: 172.16.10.92
  username: eleme
  password: eleMe
  database: eleme
  port: 3306

alpha:
  host:
  username:
  password:
  database:
  port: 3306

debug:
  host: 127.0.0.1
  username: root
  password: king258angel@
  database: ui_auto_web
  port: 3306
