host:
  alpha:
    restapi: http://localhost:3000
    m:
  beta:
    restapi:
    m:
  ppe:
    restapi:
    m:
DB:
  alpha:
  	eus:
      host:
      username:
      password:
      port:
      database:
    eos:
      host:
      username:
      password:
      port:
      database:
    eps:
      host:
      username:
      password:
      port:
      database:
    ers:
      host:
      username:
      password:
      port:
      database:
  beta:
    eus:
      host:
      username:
      password:
      port:
      database:
    eos:
      host:
      username:
      password:
      port:
      database:
    eps:
      host:
      username:
      password:
      port:
      database:
    ers:
      host:
      username:
      password:
      port:
      database:
  ppe:
    eus:
      host:
      username:
      password:
      port:
      database:
    eos:
      host:
      username:
      password:
      port:
      database:
    eps:
      host:
      username:
      password:
      port:
      database:
    ers:
      host:
      username:
      password:
      port:
      database: